import { Footer } from "@/components/Footer";

const termsSections = [
  {
    id: "01",
    icon: "✅",
    title: "Acceptance of Terms",
    content:
      "These Terms of Service constitute a legally binding agreement between you (User) and Cookify governing your access to and use of the platform, including our website, API, and all related services.",
    extra:
      "By creating an account, clicking Sign Up, or otherwise accessing Cookify, you confirm that you have read, understood, and agreed to be bound by these Terms and our Privacy Policy. If you do not agree, please discontinue use immediately.",
  },
  {
    id: "02",
    icon: "👤",
    title: "Eligibility",
    bullets: [
      "Be at least 13 years of age (or the minimum digital age of consent in your country)",
      "Provide accurate and complete registration information",
      "Not be prohibited from using the service under applicable laws",
      "Not have a previously terminated Cookify account",
    ],
    content:
      "By registering, you confirm you meet these requirements. We reserve the right to verify eligibility and suspend accounts if requirements are not met.",
  },
  {
    id: "03",
    icon: "🔐",
    title: "Your Account",
    table: [
      { col1: "🔐 Password Security", col2: "You are responsible for maintaining the confidentiality of your password and credentials" },
      { col1: "📧 Accurate Info", col2: "Provide a valid email address and keep your account information up to date" },
      { col1: "🚫 No Sharing", col2: "Your account is personal — do not share credentials or allow unauthorized access" },
      { col1: "⚡ Prompt Reporting", col2: "Notify us immediately at security@cookify.app if you suspect unauthorized access" },
    ],
    content:
      "Cookify is not liable for any loss resulting from unauthorized use of your account that arises from your failure to safeguard your credentials.",
  },
  {
    id: "04",
    icon: "🎮",
    title: "Acceptable Use",
    content: "Cookify is built for culinary inspiration and recipe discovery. Please use it responsibly:",
    doList: [
      "Generate recipes for personal or household use",
      "Save and organise your favourite AI-generated recipes",
      "Share individual recipes with friends or family",
      "Use dietary filters (Veg / Non-Veg) freely",
    ],
    dontList: [
      "Scrape or mass-collect recipes via automated means",
      "Attempt to reverse-engineer our AI prompts or API",
      "Use Cookify for commercial recipe reselling without permission",
      "Upload harmful, abusive, or illegal content",
    ],
    extra: "Violations may result in immediate account suspension without notice.",
  },
  {
    id: "05",
    icon: "🤖",
    title: "AI-Generated Content",
    highlight:
      "Recipes are generated by Google GenAI and are provided for inspiration only. Cookify does not guarantee accuracy, nutritional correctness, food safety, or suitability for specific dietary requirements or medical conditions.",
    bullets: [
      "AI-generated recipes may contain errors, unusual combinations, or incorrect cooking times",
      "Apply your own judgement and cooking knowledge when following any recipe",
      "Cookify is not responsible for allergic reactions or foodborne illness from generated recipes",
      "If you have dietary restrictions or medical conditions, consult a qualified professional",
    ],
  },
  {
    id: "06",
    icon: "©️",
    title: "Intellectual Property",
    bullets: [
      "Your content: Ingredients and preferences you provide remain yours — we make no claim over your inputs",
      "AI output: Generated recipes may be used for personal purposes; Cookify makes no warranty of originality",
      "Platform IP: You may not copy, modify, or distribute Cookify's codebase or design without written consent",
      "Trademarks: Cookify and the Cookify logo are trademarks — do not use them without permission",
    ],
  },
  {
    id: "07",
    icon: "⚠️",
    title: "Limitation of Liability",
    bullets: [
      "Cookify is provided \"as is\" without warranties of any kind, express or implied",
      "We do not warrant that the service will be uninterrupted, error-free, or always available",
      "We are not liable for indirect, incidental, or consequential damages from your use of Cookify",
      "Our total liability shall not exceed the amount you paid us in the past 12 months",
      "We are not responsible for interruptions caused by third-party services (Google, MongoDB)",
    ],
    content:
      "Some jurisdictions do not allow limitation of liability for personal injury; in such cases the above may not apply to the fullest extent.",
  },
  {
    id: "08",
    icon: "🚪",
    title: "Termination",
    bullets: [
      "By you: Delete your account anytime from settings — personal data removed within 30 days",
      "By us: We may suspend or terminate your account immediately for Terms violations, without prior notice",
      "Effect: Upon termination your right to use Cookify ceases. Provisions that by nature should survive remain in effect",
    ],
  },
  {
    id: "09",
    icon: "📝",
    title: "Changes to These Terms",
    bullets: [
      "We will update the Last Updated date at the top of this page",
      "We will notify you via email or in-app notification at least 14 days before changes take effect",
      "Continued use of Cookify after changes take effect constitutes acceptance of the new Terms",
    ],
    content:
      "If you disagree with any changes, please stop using Cookify and delete your account before the new Terms take effect.",
  },
];

export default function TermsOfService() {
  return (
    <div className="relative w-full py-20">

      {/* ===== HERO ===== */}
      {/* <div className="relative mt-16 w-full min-h-[40vh] sm:min-h-[50vh] pt-10 sm:pt-20 overflow-hidden bg-gradient-to-br from-orange-950 via-orange-900 to-amber-900 flex items-center justify-center">
        <div className="absolute top-0 right-0 w-72 h-72 bg-orange-500/10 rounded-full blur-3xl -translate-y-10 translate-x-10" />
        <div className="absolute bottom-0 left-0 w-56 h-56 bg-amber-400/10 rounded-full blur-3xl translate-y-10 -translate-x-10" />

        <div className="relative z-20 flex flex-col gap-4 items-center text-center px-4 max-w-3xl">
          <span className="inline-flex items-center gap-2 bg-orange-500/20 border border-orange-400/40 text-orange-300 text-xs font-semibold uppercase tracking-widest px-4 py-2 rounded-full">
            📋 Legal Document
          </span>
          <h1 className="text-3xl sm:text-5xl md:text-6xl font-bold text-white">
            Terms of <span className="text-orange-400 italic font-serif">Service</span>
          </h1>
          <p className="text-sm sm:text-base text-orange-100/70 max-w-xl">
            The rules that keep Cookify fair and safe for everyone.
          </p>
          <div className="flex flex-wrap justify-center gap-6 mt-4">
            {[
              { label: "Effective Date", value: "April 1, 2026" },
              { label: "Last Updated", value: "April 1, 2026" },
              { label: "Jurisdiction", value: "India (and globally)" },
            ].map((m) => (
              <div key={m.label} className="flex flex-col items-center">
                <span className="text-[10px] uppercase tracking-widest text-orange-300/50 mb-1">{m.label}</span>
                <span className="text-sm font-semibold text-white">{m.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div> */}

      {/* ===== ACCEPTANCE BANNER ===== */}
      {/* <div className="bg-orange-50 border-b border-orange-200 px-4 sm:px-10 py-4 flex items-start gap-3">
        <span className="text-orange-500 text-lg mt-0.5">⚠️</span>
        <p className="text-sm text-orange-800">
          <strong>By using Cookify, you agree to these terms.</strong> Please read carefully before creating an account or generating recipes.
        </p>
      </div> */}

      {/* ===== SECTIONS ===== */}
      <section className="flex flex-col items-center gap-10 my-10 mt-16 px-4">
        <h2 className="text-2xl sm:text-4xl font-bold text-black text-center">
          Your Agreement with Cookify
        </h2>

        <div className="w-full max-w-4xl flex flex-col gap-8">
          {termsSections.map((sec) => (
            <div
              key={sec.id}
              className="bg-gray-50 rounded-2xl px-6 sm:px-10 py-8 shadow-sm"
            >
              {/* Header */}
              <div className="flex items-center gap-4 mb-5">
                <div className="w-10 h-10 rounded-xl bg-orange-100 border border-orange-200 flex items-center justify-center text-xs font-bold text-orange-500 flex-shrink-0">
                  {sec.id}
                </div>
                <h3 className="text-lg sm:text-xl font-bold text-black flex items-center gap-2">
                  <span>{sec.icon}</span> {sec.title}
                </h3>
              </div>

              {/* Opening paragraph */}
              {sec.content && (
                <p className="text-sm text-zinc-600 mb-4">{sec.content}</p>
              )}

              {/* Highlight box */}
              {sec.highlight && (
                <div className="bg-orange-50 border border-orange-200 border-l-4 border-l-orange-500 rounded-xl p-4 mb-4">
                  <p className="text-sm text-orange-900">{sec.highlight}</p>
                </div>
              )}

              {/* Bullet list */}
              {sec.bullets && (
                <ul className="flex flex-col gap-3 mb-4">
                  {sec.bullets.map((b, i) => (
                    <li key={i} className="flex items-start gap-3 text-sm text-zinc-600">
                      <span className="w-2 h-2 rounded-full bg-orange-400 flex-shrink-0 mt-1.5" />
                      {b}
                    </li>
                  ))}
                </ul>
              )}

              {/* Do / Don't grid */}
              {sec.doList && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 my-4">
                  <div className="bg-green-50 border border-green-200 rounded-xl p-5">
                    <p className="text-xs font-bold uppercase tracking-wider text-green-700 mb-3">✅ You May</p>
                    <ul className="flex flex-col gap-2">
                      {sec.doList.map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-green-900">
                          <span className="text-green-500 mt-0.5">✓</span> {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div className="bg-red-50 border border-red-200 rounded-xl p-5">
                    <p className="text-xs font-bold uppercase tracking-wider text-red-700 mb-3">🚫 You Must Not</p>
                    <ul className="flex flex-col gap-2">
                      {sec.dontList.map((item, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-red-900">
                          <span className="text-red-400 mt-0.5">✗</span> {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              )}

              {/* Table */}
              {sec.table && (
                <div className="overflow-x-auto rounded-xl border border-gray-200 mb-4">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="bg-orange-950 text-orange-100 text-xs uppercase tracking-wider">
                        <th className="text-left px-5 py-3 font-semibold">Responsibility</th>
                        <th className="text-left px-5 py-3 font-semibold">Details</th>
                      </tr>
                    </thead>
                    <tbody>
                      {sec.table.map((row, i) => (
                        <tr key={i} className={i % 2 === 1 ? "bg-white" : "bg-gray-50"}>
                          <td className="px-5 py-3 font-medium text-zinc-700 whitespace-nowrap">{row.col1}</td>
                          <td className="px-5 py-3 text-zinc-500">{row.col2}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {/* Trailing content / extra */}
              {sec.extra && (
                <p className="text-sm text-zinc-500 mt-2">{sec.extra}</p>
              )}

              {/* Second paragraph (when content is an opener and extra is the closer) */}
              {!sec.content && !sec.extra && !sec.table && !sec.doList && !sec.highlight && !sec.bullets && sec.content && (
                <p className="text-sm text-zinc-500">{sec.content}</p>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* ===== CONTACT SECTION ===== */}
      {/* <section className="flex flex-col items-center justify-center gap-5 my-10 mt-16 py-14 px-4 bg-white">
        <h2 className="text-2xl sm:text-4xl text-black font-bold text-center">
          What Our Users Say
        </h2>
        <p className="text-sm sm:text-base text-zinc-500 text-center max-w-md">
          Questions about our terms or your account? Our team responds within 30 business days.
        </p>

        <div className="w-full max-w-sm bg-gradient-to-br from-orange-950 to-amber-900 rounded-2xl p-8 flex flex-col items-center gap-4 text-center shadow-lg">
          <span className="text-4xl">⚖️</span>
          <h3 className="text-white font-bold text-lg">Legal & Support Team</h3>
          <p className="text-orange-200/70 text-sm">
            Disputes, account issues, or questions about these Terms.
          </p>
          <a
            href="mailto:legal@cookify.app"
            className="bg-orange-500 hover:bg-orange-400 transition-colors text-white text-sm font-semibold px-6 py-3 rounded-xl"
          >
            ⚖️ legal@cookify.app
          </a>
        </div>

        <p className="text-xs text-zinc-400 text-center max-w-md mt-2">
          These Terms shall be governed by and construed in accordance with the laws of India. Any disputes shall be subject to the exclusive jurisdiction of competent courts in India.
        </p>
      </section> */}

      <Footer />
    </div>
  );
}